services:
  diffuzzer_db:
    container_name: diffuzzer_db
    image: postgres:17
    restart: always
    shm_size: 128mb
    volumes:
      - "untitled-crud-test:/var/lib/postgresql/data"
      - ./backend/internal/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: fuzzer_db
      POSTGRES_USER: fuzzer_user
      POSTGRES_PASSWORD: fuzzer_password
      DB_HOST: diffuzzer_db
      DB_PORT: 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fuzzer_user -d fuzzer_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  diffuzzer_backend:
    container_name: diffuzzer_backend
    build: ./backend
    restart: always
    environment:
      DB_USER: fuzzer_user
      DB_PASSWORD: fuzzer_password
      DB_HOST: diffuzzer_db
      DB_NAME: fuzzer_db
      DB_PORT: 5432
    depends_on:
      diffuzzer_db:
        condition: service_healthy

  diffuzzer_nginx:
    container_name: diffuzzer_nginx
    build: ./frontend
    restart: always
    ports:
      - "0.0.0.0:1337:1337"

volumes:
  untitled-crud-test:
