services:
  untitled-gateway:
    runtime: runc
    container_name: untitled-frontend
    build: ./frontend
    ports: 
    - "127.0.0.1:8080:8080"
    depends_on:
      - untitled-backend

  untitled-backend:
    runtime: runc
    container_name: untitled-backend
    build: ./backend
    environment:
      POSTGRES_HOST: untitled-db
      POSTGRES_PORT: 5432
      POSTGRES_DB: postgres
      POSTGRES_USER: user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      untitled-db:
        condition: service_healthy

  untitled-db:
    runtime: runc
    container_name: untitled-db
    build: ./db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 3s
      timeout: 2s
      retries: 10
