services:
  db:
    image: postgres:15
    restart: always
    shm_size: 128mb
    volumes:
      - "untitled-crud-test:/var/lib/postgresql/data"
      - ./internal/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: fuzzer_db
      POSTGRES_USER: fuzzer_user
      POSTGRES_PASSWORD: fuzzer_password
      DB_HOST: database
      DB_PORT: 5432
    ports:
      - "1200:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fuzzer_user -d fuzzer_db"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  untitled-crud-test:
    driver: local

